version: "3.3"

services:
  image-previewer:
    container_name: image-previewer
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      LOG_LEVEL: "info"